In [1]:
import pandas as pd

In [2]:
# step-1: create data frame using list
names = ['Ramesh','Suresh','Sathish']

In [4]:
#pd.DataFrame(data,index,columns)

pd.DataFrame(names,columns=['Names'])

     Names
0   Ramesh
1   Suresh
2  Sathish

In [5]:
pd.DataFrame(names,index=['A','B','C'],columns=['Names'])

     Names
A   Ramesh
B   Suresh
C  Sathish

In [12]:
#step-2
names = ['Ramesh','Suresh','Sathish']
age=[20,22,24]
#pd.DataFrame(data,index,columns)
pd.DataFrame(zip(names,age),columns = ['Names','Age'])

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [13]:
#step - 3 = create a dataframe using dict
d={'Names':['Ramesh','Suresh','Sathish'],
   'Age':[20,22,24]}
d

{'Names': ['Ramesh', 'Suresh', 'Sathish'], 'Age': [20, 22, 24]}

In [17]:
pd.DataFrame(d)

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [18]:
#step-4: selection updation and add column
#select the column
#update the column
#add new column

In [22]:
d={'Names':['Ramesh','Suresh','Sathish'],
   'Age':[20,22,24]}
df=pd.DataFrame(d)
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [24]:
#select the column
df['Names']

0     Ramesh
1     Suresh
2    Sathish
Name: Names, dtype: object

In [26]:
#update the column
df['Age']=[30,32,34]

In [27]:
df

     Names  Age
0   Ramesh   30
1   Suresh   32
2  Sathish   34

In [28]:
#add new column
df['City'] = ['Hyd','Blr','Pune']

In [29]:
df

     Names  Age  City
0   Ramesh   30   Hyd
1   Suresh   32   Blr
2  Sathish   34  Pune

In [33]:
#specific value
#inplace=we need to tell the python that output should be overwrite
df.replace('Suresh','Mahesh',inplace=True)

In [34]:
df

     Names  Age  City
0   Ramesh   30   Hyd
1   Mahesh   32   Blr
2  Sathish   34  Pune

In [35]:
#condition
import numpy as np
np.where()

In [37]:
df['Names'] == 'Mahesh'

0    False
1     True
2    False
Name: Names, dtype: bool

In [39]:
l = []
for i,j in zip(df['Names'],df['Age']):
    if i=='Mahesh':
        l.append(45)
    else:
        l.append(j)
l
df['Age'] = l

In [40]:
df

     Names  Age  City
0   Ramesh   30   Hyd
1   Mahesh   45   Blr
2  Sathish   34  Pune

In [42]:
import numpy as np
df['Age'] = np.where(df['Names']=='Mahesh',65,df['Age'])
df

     Names  Age  City
0   Ramesh   30   Hyd
1   Mahesh   65   Blr
2  Sathish   34  Pune

In [43]:
#How to drop a column
df

     Names  Age  City
0   Ramesh   30   Hyd
1   Mahesh   65   Blr
2  Sathish   34  Pune

In [44]:
#df.drop(labels,axis,index,column)
#by default axis=0, index
df.drop('City',axis=1) #inplace

     Names  Age
0   Ramesh   30
1   Mahesh   65
2  Sathish   34

In [45]:
df

     Names  Age  City
0   Ramesh   30   Hyd
1   Mahesh   65   Blr
2  Sathish   34  Pune

In [47]:
df.drop(columns=['City'])

     Names  Age
0   Ramesh   30
1   Mahesh   65
2  Sathish   34